development:
  default:
    host: localhost
    port: 27017

test:
  default:
    host: localhost
    port: 27017

production:
  default:
    host: localhost
    port: 27017

benchmarking:
  default:
    host: localhost
    port: 27017
