development:
    hostname: localhost
    exchange: logjam-development-exchange
    queue:    logjam-development-queue

test:
    hostname: localhost
    exchange: logjam-test-exchange
    queue:    logjam-test-queue

production:
    hostname: localhost
    exchange: logjam-production-exchange
    queue:    logjam-production-queue
