development:
    host:     localhost
    exchange: logjam-development-exchange
    queue:    logjam-development-queue

test:
    host:     localhost
    exchange: logjam-test-exchange
    queue:    logjam-test-queue

production:
    host:     localhost
    exchange: logjam-production-exchange
    queue:    logjam-production-queue
