development:
  default:
    host: <%= ENV["LOGJAM_DEVELOPMENT_DB"] || "localhost" %>
    port: 27017

test:
  default:
    host: <%= ENV["LOGJAM_TEST_DB"] || "localhost" %>
    port: 27017

production:
  default:
    host: <%= ENV["LOGJAM_PRODUCTION_DB"] || "localhost" %>
    port: 27017

benchmarking:
  default:
    host: <%= ENV["LOGJAM_DEVELOPMENT_DB"] || "localhost" %>
    port: 27017
